### ISSUE TITLE
matmul operation does not work in current version 

### ISSUE THREAD

**Issue by Gregoire-Phillips** [mc2-project/cerebro#3]
The matmul(A,B) matrix multiplication operator is throwing an error indicating that it expects seven arguments instead of two. This makes regression operations impossible in the current iteration. Is there a way around this? 

Attached is the error:

![image](https://user-images.githubusercontent.com/63256579/117047205-761c4b80-acc6-11eb-8cca-2b3337b789c9.png)

**Comment by weikengchen** [comment]
I think it should not prevent you from doing regression. The seven parameters are:
```
matmul(X_T, y_data, num_cols, num_rows, num_rows, 1, sfix)
```

A, B, A's first dimension, A's second dimension, B's first dimension (should = A's second dimension), B's second dimension, type of A/B

where the rest of the parameters only depend on the shape of the matrix, and are likely constants? If in your case it is not constant, due to the limit of SCALE-MAMBA's programming language, at this moment the SCALE-MAMBA's VM model does not enable such flexibility, and the algorithm may need some changes.

**Comment by weikengchen** [comment]
It seems that some of our test examples may have called an old version of `matmul` (e.g., `test_lr_tiny` and `test_lr_policy`). Will update them soon. @wzheng @ryandeng1

**Comment by Gregoire-Phillips** [comment]
Got it, thanks! Yeah, the documentation definitely doesn't make this clear as written -- it currently only shows two args for the matmul operator. I got this error when running test_lr and would like to work with lr moving forward, so I'll update the .mpc with the additional args and run from there. Thanks again!

**Comment by weikengchen** [comment]
This commit fixes the `test_lr` for a similar situation, which can be used for your reference:

https://github.com/mc2-project/cerebro/commit/5a091b433f66a4d29c659e9e1731f1ac573472c0

**Comment by Gregoire-Phillips** [comment]
Awesome, thanks!
